//! Filesystem implementation
//!
//! ⚠️ STATUS: UNVERIFIED - Agent-B Delivery
//! This code is generated by Agent-B and has NOT been verified by Master Agent.
//! DO NOT USE IN PRODUCTION.
//!
//! Native filesystem implementation supporting Windows, macOS, and Linux.

use async_trait::async_trait;
use std::path::{Path, PathBuf};
use std::time::SystemTime;

use syncthing_core::{traits::FileSystem, BlockHash, FileInfo, FileType, Result, SyncthingError};
use tokio::fs;
use tokio::io::{AsyncReadExt, AsyncSeekExt, AsyncWriteExt};

use crate::ignore::IgnorePatterns;
use crate::scanner::scan_file;

/// Default block size for file hashing (128 KB)
const DEFAULT_BLOCK_SIZE: usize = 128 * 1024;

/// Native filesystem implementation
///
/// Provides cross-platform filesystem operations with support for:
/// - Block-level file reads/writes
/// - SHA-256 block hashing
/// - Directory scanning
/// - Atomic file operations
#[derive(Debug, Clone)]
pub struct NativeFileSystem {
    root: PathBuf,
    block_size: usize,
}

impl NativeFileSystem {
    /// Create a new filesystem at the given root path
    ///
    /// # Arguments
    /// * `root` - The root directory for all filesystem operations
    ///
    /// # Example
    /// ```
    /// use syncthing_fs::NativeFileSystem;
    /// use std::path::Path;
    ///
    /// let fs = NativeFileSystem::new("/path/to/folder");
    /// ```
    pub fn new(root: impl AsRef<Path>) -> Self {
        Self {
            root: root.as_ref().to_path_buf(),
            block_size: DEFAULT_BLOCK_SIZE,
        }
    }

    /// Create a new filesystem with a custom block size
    ///
    /// # Arguments
    /// * `root` - The root directory for all filesystem operations
    /// * `block_size` - The block size to use for hashing operations
    pub fn with_block_size(root: impl AsRef<Path>, block_size: usize) -> Self {
        Self {
            root: root.as_ref().to_path_buf(),
            block_size,
        }
    }

    /// Get the full path for a relative path
    fn full_path(&self, path: &Path) -> PathBuf {
        self.root.join(path)
    }

    /// Scan a directory recursively with ignore patterns
    ///
    /// Returns FileInfo for all files, directories, and symlinks
    /// that are not ignored by the given patterns.
    ///
    /// # Arguments
    /// * `path` - Relative path within the root to scan
    /// * `ignore` - Ignore patterns to filter entries
    pub async fn scan_directory_with_ignore(
        &self,
        path: &Path,
        ignore: &IgnorePatterns,
    ) -> Result<Vec<FileInfo>> {
        let full_path = self.full_path(path);
        let root = full_path.clone();
        let ignore = ignore.clone();

        // Check if path exists and is a directory
        let Ok(metadata) = fs::metadata(&full_path).await else {
            return Ok(Vec::new());
        };

        if !metadata.is_dir() {
            return Err(SyncthingError::io(format!(
                "Path is not a directory: {}",
                full_path.display()
            )));
        }

        // Collect entries in a blocking task to avoid blocking the async runtime
        let entries = tokio::task::spawn_blocking(move || {
            let mut results = Vec::new();
            let mut walker = walkdir::WalkDir::new(&full_path)
                .follow_links(false) // Don't follow symlinks by default
                .into_iter();

            while let Some(entry) = walker.next() {
                let entry = match entry {
                    Ok(e) => e,
                    Err(e) => return Err(SyncthingError::io(e.to_string())),
                };

                let entry_path = entry.path();

                // Get relative path
                let Ok(rel_path) = entry_path.strip_prefix(&root) else {
                    continue;
                };
                // Normalize path separators for cross-platform consistency
                let rel_path_str = rel_path.to_string_lossy().replace('\\', "/");

                // Skip root directory itself
                if rel_path_str.is_empty() {
                    continue;
                }

                // Check ignore patterns for directories: prune if ignored
                if entry.file_type().is_dir() && ignore.is_ignored(Path::new(&rel_path_str)) {
                    walker.skip_current_dir();
                    continue;
                }

                // Check ignore patterns for files
                if !entry.file_type().is_dir() && ignore.is_ignored(Path::new(&rel_path_str)) {
                    continue;
                }

                results.push((entry_path.to_path_buf(), rel_path_str));
            }

            Ok::<_, SyncthingError>(results)
        })
        .await
        .map_err(|e| SyncthingError::io(e.to_string()))?;

        let entries = entries?;

        let mut results = Vec::new();
        for (entry_path, rel_path_str) in entries {
            let info = build_file_info(&entry_path, &rel_path_str).await?;
            results.push(info);
        }

        Ok(results)
    }
}

#[async_trait]
impl FileSystem for NativeFileSystem {
    /// Read a block from a file at the given offset
    ///
    /// Reads up to `size` bytes from the file at `path` starting at `offset`.
    /// Returns the actual bytes read, which may be less than `size` if at EOF.
    async fn read_block(&self, path: &Path, offset: u64, size: usize) -> Result<Vec<u8>> {
        let full_path = self.full_path(path);

        let mut file = fs::File::open(&full_path)
            .await
            .map_err(SyncthingError::Io)?;

        // Seek to offset
        file.seek(std::io::SeekFrom::Start(offset))
            .await
            .map_err(SyncthingError::Io)?;

        // Read data
        let mut buffer = vec![0u8; size];
        let bytes_read = file.read(&mut buffer).await.map_err(SyncthingError::Io)?;
        buffer.truncate(bytes_read);

        Ok(buffer)
    }

    /// Write a block to a file at the given offset
    ///
    /// Creates the file if it doesn't exist. Parent directories are created automatically.
    async fn write_block(&self, path: &Path, offset: u64, data: &[u8]) -> Result<()> {
        let full_path = self.full_path(path);

        // Create parent directories if needed
        if let Some(parent) = full_path.parent() {
            fs::create_dir_all(parent)
                .await
                .map_err(SyncthingError::Io)?;
        }

        // Open or create file (truncate=false because we seek to offset and write blocks)
        let mut file = fs::OpenOptions::new()
            .write(true)
            .create(true)
            .truncate(false)
            .open(&full_path)
            .await
            .map_err(SyncthingError::Io)?;

        // Seek to offset
        file.seek(std::io::SeekFrom::Start(offset))
            .await
            .map_err(SyncthingError::Io)?;

        // Write data
        file.write_all(data).await.map_err(SyncthingError::Io)?;

        // Ensure data is flushed to disk
        file.sync_data().await.map_err(SyncthingError::Io)?;

        Ok(())
    }

    /// Calculate block hashes for a file
    ///
    /// Reads the file and computes SHA-256 hash for each block.
    async fn hash_file(&self, path: &Path) -> Result<Vec<BlockHash>> {
        let full_path = self.full_path(path);
        let file_info = scan_file(&full_path, self.block_size).await?;
        Ok(file_info
            .blocks
            .iter()
            .map(|b| {
                let bytes: [u8; 32] = b.hash.as_slice().try_into().unwrap_or([0u8; 32]);
                BlockHash::from_bytes(bytes)
            })
            .collect())
    }

    /// Scan a directory recursively
    ///
    /// Returns FileInfo for all files, directories, and symlinks.
    async fn scan_directory(&self, path: &Path) -> Result<Vec<FileInfo>> {
        self.scan_directory_with_ignore(path, &IgnorePatterns::new())
            .await
    }

    /// Get file info for a single file
    async fn file_info(&self, path: &Path) -> Result<FileInfo> {
        let full_path = self.full_path(path);
        let rel_path_str = path.to_string_lossy().to_string();
        build_file_info(&full_path, &rel_path_str).await
    }

    /// Remove a file or directory
    async fn remove(&self, path: &Path) -> Result<()> {
        let full_path = self.full_path(path);

        let metadata = fs::metadata(&full_path).await.map_err(SyncthingError::Io)?;

        if metadata.is_dir() {
            fs::remove_dir_all(&full_path)
                .await
                .map_err(SyncthingError::Io)?;
        } else {
            fs::remove_file(&full_path)
                .await
                .map_err(SyncthingError::Io)?;
        }

        Ok(())
    }

    /// Create a directory and all parent directories
    async fn create_dir(&self, path: &Path) -> Result<()> {
        let full_path = self.full_path(path);
        fs::create_dir_all(&full_path)
            .await
            .map_err(SyncthingError::Io)?;
        Ok(())
    }

    /// Check if path exists
    async fn exists(&self, path: &Path) -> Result<bool> {
        let full_path = self.full_path(path);
        Ok(full_path.exists())
    }

    /// Rename/move a file
    ///
    /// On Windows, handles cross-device moves, sharing violations, and
    /// access-denied errors by falling back to remove+rename.
    async fn rename(&self, from: &Path, to: &Path) -> Result<()> {
        let from_full = self.full_path(from);
        let to_full = self.full_path(to);

        // Create parent directories for destination
        if let Some(parent) = to_full.parent() {
            fs::create_dir_all(parent)
                .await
                .map_err(SyncthingError::Io)?;
        }

        // Try atomic rename first
        match fs::rename(&from_full, &to_full).await {
            Ok(()) => return Ok(()),
            Err(e) => {
                // If cross-device link error, do copy+delete
                #[cfg(unix)]
                if e.raw_os_error() == Some(libc::EXDEV) {
                    return copy_and_delete(&from_full, &to_full).await;
                }

                #[cfg(windows)]
                {
                    let raw = e.raw_os_error();
                    // ERROR_NOT_SAME_DEVICE (17): cross-device move
                    if raw == Some(17) {
                        return copy_and_delete(&from_full, &to_full).await;
                    }
                    // ERROR_SHARING_VIOLATION (32) or ERROR_ACCESS_DENIED (5):
                    // target file locked by another process, try remove+rename
                    if raw == Some(32) || raw == Some(5) {
                        if to_full.exists() {
                            let _ = fs::remove_file(&to_full).await;
                        }
                        return fs::rename(&from_full, &to_full)
                            .await
                            .map_err(SyncthingError::Io);
                    }
                }

                Err(SyncthingError::Io(e))
            }
        }
    }
}

/// Build FileInfo from a filesystem path
async fn build_file_info(path: &Path, name: &str) -> Result<FileInfo> {
    let metadata = fs::symlink_metadata(path)
        .await
        .map_err(SyncthingError::Io)?;

    let mut info = FileInfo::new(name);
    info.size = metadata.len() as i64;
    let duration = metadata
        .modified()
        .unwrap_or(SystemTime::UNIX_EPOCH)
        .duration_since(SystemTime::UNIX_EPOCH)
        .unwrap_or_default();
    info.modified_s = duration.as_secs() as i64;
    info.modified_ns = duration.subsec_nanos() as i32;

    if metadata.file_type().is_symlink() {
        info.file_type = FileType::Symlink;
    } else if metadata.is_dir() {
        info.file_type = FileType::Directory;
    } else {
        info.file_type = FileType::File;
    }

    // Handle symlinks
    if info.file_type == FileType::Symlink {
        let target = fs::read_link(path).await.map_err(SyncthingError::Io)?;
        info.symlink_target = Some(target.to_string_lossy().to_string());
    }

    // Get permissions (Unix-style)
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        info.permissions = metadata.permissions().mode();
    }

    #[cfg(windows)]
    {
        // Windows doesn't have Unix-style permissions
        // Use default based on whether it's a directory
        info.permissions = if info.file_type == FileType::Directory {
            0o755
        } else {
            0o644
        };

        // Check for read-only flag
        if metadata.permissions().readonly() {
            info.permissions &= 0o555; // Remove write bits
        }
    }

    // If it's a regular file, compute block hashes
    if metadata.is_file() && info.file_type != FileType::Symlink {
        let file_info = scan_file(path, DEFAULT_BLOCK_SIZE).await?;
        info.blocks = file_info.blocks;
    }

    Ok(info)
}

/// Copy a file and then delete the original (for cross-device moves)
async fn copy_and_delete(from: &Path, to: &Path) -> Result<()> {
    // Copy file
    fs::copy(from, to).await.map_err(SyncthingError::Io)?;

    // Remove original
    fs::remove_file(from).await.map_err(SyncthingError::Io)?;

    Ok(())
}

/// Write data atomically by writing to temp file and renaming
///
/// This ensures that readers never see partial writes.
pub async fn atomic_write(path: &Path, data: &[u8]) -> Result<()> {
    // Create temp file in the same directory with a unique suffix
    let unique_suffix = SystemTime::now()
        .duration_since(SystemTime::UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos()
        .to_string();
    let temp_path = path.with_extension(format!("tmp.{}", unique_suffix));

    // Write to temp file
    let mut file = fs::File::create(&temp_path)
        .await
        .map_err(SyncthingError::Io)?;

    file.write_all(data).await.map_err(SyncthingError::Io)?;
    file.sync_data().await.map_err(SyncthingError::Io)?;
    drop(file);

    // Atomically rename temp file to target
    fs::rename(&temp_path, path)
        .await
        .map_err(SyncthingError::Io)?;

    Ok(())
}

#[cfg(test)]
mod tests;
