//! Filesystem implementation
//!
//! ⚠️ STATUS: UNVERIFIED - Agent-B Delivery
//! This code is generated by Agent-B and has NOT been verified by Master Agent.
//! DO NOT USE IN PRODUCTION.
//!
//! Native filesystem implementation supporting Windows, macOS, and Linux.

use async_trait::async_trait;
use std::path::{Path, PathBuf};
use std::time::SystemTime;

use syncthing_core::{
    traits::FileSystem,
    BlockHash, FileInfo, FileType, Result, SyncthingError,
};
use tokio::fs;
use tokio::io::{AsyncReadExt, AsyncSeekExt, AsyncWriteExt};

use crate::ignore::IgnorePatterns;
use crate::scanner::scan_file;

/// Default block size for file hashing (128 KB)
const DEFAULT_BLOCK_SIZE: usize = 128 * 1024;

/// Native filesystem implementation
///
/// Provides cross-platform filesystem operations with support for:
/// - Block-level file reads/writes
/// - SHA-256 block hashing
/// - Directory scanning
/// - Atomic file operations
#[derive(Debug, Clone)]
pub struct NativeFileSystem {
    root: PathBuf,
    block_size: usize,
}

impl NativeFileSystem {
    /// Create a new filesystem at the given root path
    ///
    /// # Arguments
    /// * `root` - The root directory for all filesystem operations
    ///
    /// # Example
    /// ```
    /// use syncthing_fs::NativeFileSystem;
    /// use std::path::Path;
    ///
    /// let fs = NativeFileSystem::new("/path/to/folder");
    /// ```
    pub fn new(root: impl AsRef<Path>) -> Self {
        Self {
            root: root.as_ref().to_path_buf(),
            block_size: DEFAULT_BLOCK_SIZE,
        }
    }

    /// Create a new filesystem with a custom block size
    ///
    /// # Arguments
    /// * `root` - The root directory for all filesystem operations
    /// * `block_size` - The block size to use for hashing operations
    pub fn with_block_size(root: impl AsRef<Path>, block_size: usize) -> Self {
        Self {
            root: root.as_ref().to_path_buf(),
            block_size,
        }
    }

    /// Get the full path for a relative path
    fn full_path(&self, path: &Path) -> PathBuf {
        self.root.join(path)
    }

    /// Scan a directory recursively with ignore patterns
    ///
    /// Returns FileInfo for all files, directories, and symlinks
    /// that are not ignored by the given patterns.
    ///
    /// # Arguments
    /// * `path` - Relative path within the root to scan
    /// * `ignore` - Ignore patterns to filter entries
    pub async fn scan_directory_with_ignore(
        &self,
        path: &Path,
        ignore: &IgnorePatterns,
    ) -> Result<Vec<FileInfo>> {
        let full_path = self.full_path(path);
        let root = full_path.clone();
        let ignore = ignore.clone();

        // Check if path exists and is a directory
        let metadata = match fs::metadata(&full_path).await {
            Ok(m) => m,
            Err(_) => return Ok(Vec::new()),
        };

        if !metadata.is_dir() {
            return Err(SyncthingError::io(format!(
                "Path is not a directory: {}",
                full_path.display()
            )));
        }

        // Collect entries in a blocking task to avoid blocking the async runtime
        let entries = tokio::task::spawn_blocking(move || {
            let mut results = Vec::new();
            let mut walker = walkdir::WalkDir::new(&full_path)
                .follow_links(false) // Don't follow symlinks by default
                .into_iter();

            while let Some(entry) = walker.next() {
                let entry = match entry {
                    Ok(e) => e,
                    Err(e) => return Err(SyncthingError::io(e.to_string())),
                };

                let entry_path = entry.path();

                // Get relative path
                let rel_path = match entry_path.strip_prefix(&root) {
                    Ok(p) => p,
                    Err(_) => continue,
                };
                // Normalize path separators for cross-platform consistency
                let rel_path_str = rel_path.to_string_lossy().replace('\\', "/");

                // Skip root directory itself
                if rel_path_str.is_empty() {
                    continue;
                }

                // Check ignore patterns for directories: prune if ignored
                if entry.file_type().is_dir() && ignore.is_ignored(Path::new(&rel_path_str)) {
                    walker.skip_current_dir();
                    continue;
                }

                // Check ignore patterns for files
                if !entry.file_type().is_dir() && ignore.is_ignored(Path::new(&rel_path_str)) {
                    continue;
                }

                results.push((entry_path.to_path_buf(), rel_path_str));
            }

            Ok::<_, SyncthingError>(results)
        })
        .await
        .map_err(|e| SyncthingError::io(e.to_string()))?;

        let entries = entries?;

        let mut results = Vec::new();
        for (entry_path, rel_path_str) in entries {
            let info = build_file_info(&entry_path, &rel_path_str).await?;
            results.push(info);
        }

        Ok(results)
    }
}

#[async_trait]
impl FileSystem for NativeFileSystem {
    /// Read a block from a file at the given offset
    ///
    /// Reads up to `size` bytes from the file at `path` starting at `offset`.
    /// Returns the actual bytes read, which may be less than `size` if at EOF.
    async fn read_block(&self, path: &Path, offset: u64, size: usize) -> Result<Vec<u8>> {
        let full_path = self.full_path(path);

        let mut file = fs::File::open(&full_path)
            .await
            .map_err(|e| SyncthingError::Io(e))?;

        // Seek to offset
        file.seek(std::io::SeekFrom::Start(offset))
            .await
            .map_err(|e| SyncthingError::Io(e))?;

        // Read data
        let mut buffer = vec![0u8; size];
        let bytes_read = file.read(&mut buffer).await.map_err(|e| SyncthingError::Io(e))?;
        buffer.truncate(bytes_read);

        Ok(buffer)
    }

    /// Write a block to a file at the given offset
    ///
    /// Creates the file if it doesn't exist. Parent directories are created automatically.
    async fn write_block(&self, path: &Path, offset: u64, data: &[u8]) -> Result<()> {
        let full_path = self.full_path(path);

        // Create parent directories if needed
        if let Some(parent) = full_path.parent() {
            fs::create_dir_all(parent).await.map_err(|e| SyncthingError::Io(e))?;
        }

        // Open or create file
        let mut file = fs::OpenOptions::new()
            .write(true)
            .create(true)
            .open(&full_path)
            .await
            .map_err(|e| SyncthingError::Io(e))?;

        // Seek to offset
        file.seek(std::io::SeekFrom::Start(offset))
            .await
            .map_err(|e| SyncthingError::Io(e))?;

        // Write data
        file.write_all(data).await.map_err(|e| SyncthingError::Io(e))?;

        // Ensure data is flushed to disk
        file.sync_data().await.map_err(|e| SyncthingError::Io(e))?;

        Ok(())
    }

    /// Calculate block hashes for a file
    ///
    /// Reads the file and computes SHA-256 hash for each block.
    async fn hash_file(&self, path: &Path) -> Result<Vec<BlockHash>> {
        let full_path = self.full_path(path);
        let file_info = scan_file(&full_path, self.block_size).await?;
        Ok(file_info
            .blocks
            .iter()
            .map(|b| {
                let bytes: [u8; 32] = b.hash.as_slice().try_into().unwrap_or([0u8; 32]);
                BlockHash::from_bytes(bytes)
            })
            .collect())
    }

    /// Scan a directory recursively
    ///
    /// Returns FileInfo for all files, directories, and symlinks.
    async fn scan_directory(&self, path: &Path) -> Result<Vec<FileInfo>> {
        self.scan_directory_with_ignore(path, &IgnorePatterns::new())
            .await
    }

    /// Get file info for a single file
    async fn file_info(&self, path: &Path) -> Result<FileInfo> {
        let full_path = self.full_path(path);
        let rel_path_str = path.to_string_lossy().to_string();
        build_file_info(&full_path, &rel_path_str).await
    }

    /// Remove a file or directory
    async fn remove(&self, path: &Path) -> Result<()> {
        let full_path = self.full_path(path);

        let metadata = fs::metadata(&full_path).await.map_err(|e| SyncthingError::Io(e))?;

        if metadata.is_dir() {
            fs::remove_dir_all(&full_path)
                .await
                .map_err(|e| SyncthingError::Io(e))?;
        } else {
            fs::remove_file(&full_path)
                .await
                .map_err(|e| SyncthingError::Io(e))?;
        }

        Ok(())
    }

    /// Create a directory and all parent directories
    async fn create_dir(&self, path: &Path) -> Result<()> {
        let full_path = self.full_path(path);
        fs::create_dir_all(&full_path)
            .await
            .map_err(|e| SyncthingError::Io(e))?;
        Ok(())
    }

    /// Check if path exists
    async fn exists(&self, path: &Path) -> Result<bool> {
        let full_path = self.full_path(path);
        Ok(full_path.exists())
    }

    /// Rename/move a file
    ///
    /// On Windows, handles cross-device moves by copying and deleting.
    async fn rename(&self, from: &Path, to: &Path) -> Result<()> {
        let from_full = self.full_path(from);
        let to_full = self.full_path(to);

        // Create parent directories for destination
        if let Some(parent) = to_full.parent() {
            fs::create_dir_all(parent).await.map_err(|e| SyncthingError::Io(e))?;
        }

        // Try atomic rename first
        match fs::rename(&from_full, &to_full).await {
            Ok(()) => Ok(()),
            Err(e) => {
                // If cross-device link error, do copy+delete
                #[cfg(unix)]
                if e.raw_os_error() == Some(libc::EXDEV) {
                    return copy_and_delete(&from_full, &to_full).await;
                }

                #[cfg(windows)]
                if e.raw_os_error() == Some(17) {
                    // ERROR_NOT_SAME_DEVICE
                    return copy_and_delete(&from_full, &to_full).await;
                }

                Err(SyncthingError::Io(e))
            }
        }
    }
}

/// Build FileInfo from a filesystem path
async fn build_file_info(path: &Path, name: &str) -> Result<FileInfo> {
    let metadata = fs::symlink_metadata(path).await.map_err(|e| SyncthingError::Io(e))?;

    let mut info = FileInfo::new(name);
    info.size = metadata.len() as i64;
    let duration = metadata
        .modified()
        .unwrap_or_else(|_| SystemTime::UNIX_EPOCH)
        .duration_since(SystemTime::UNIX_EPOCH)
        .unwrap_or_default();
    info.modified_s = duration.as_secs() as i64;
    info.modified_ns = duration.subsec_nanos() as i32;

    if metadata.file_type().is_symlink() {
        info.file_type = FileType::Symlink;
    } else if metadata.is_dir() {
        info.file_type = FileType::Directory;
    } else {
        info.file_type = FileType::File;
    }

    // Handle symlinks
    if info.file_type == FileType::Symlink {
        let target = fs::read_link(path).await.map_err(|e| SyncthingError::Io(e))?;
        info.symlink_target = Some(target.to_string_lossy().to_string());
    }

    // Get permissions (Unix-style)
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        info.permissions = metadata.permissions().mode();
    }

    #[cfg(windows)]
    {
        // Windows doesn't have Unix-style permissions
        // Use default based on whether it's a directory
        info.permissions = if info.file_type == FileType::Directory {
            0o755
        } else {
            0o644
        };

        // Check for read-only flag
        if metadata.permissions().readonly() {
            info.permissions &= 0o555; // Remove write bits
        }
    }

    // If it's a regular file, compute block hashes
    if metadata.is_file() && info.file_type != FileType::Symlink {
        let file_info = scan_file(path, DEFAULT_BLOCK_SIZE).await?;
        info.blocks = file_info.blocks;
    }

    Ok(info)
}

/// Copy a file and then delete the original (for cross-device moves)
async fn copy_and_delete(from: &Path, to: &Path) -> Result<()> {
    // Copy file
    fs::copy(from, to).await.map_err(|e| SyncthingError::Io(e))?;

    // Remove original
    fs::remove_file(from).await.map_err(|e| SyncthingError::Io(e))?;

    Ok(())
}

/// Write data atomically by writing to temp file and renaming
///
/// This ensures that readers never see partial writes.
pub async fn atomic_write(path: &Path, data: &[u8]) -> Result<()> {
    // Create temp file in the same directory with a unique suffix
    let unique_suffix = SystemTime::now()
        .duration_since(SystemTime::UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos()
        .to_string();
    let temp_path = path.with_extension(format!("tmp.{}", unique_suffix));

    // Write to temp file
    let mut file = fs::File::create(&temp_path)
        .await
        .map_err(|e| SyncthingError::Io(e))?;

    file.write_all(data).await.map_err(|e| SyncthingError::Io(e))?;
    file.sync_data().await.map_err(|e| SyncthingError::Io(e))?;
    drop(file);

    // Atomically rename temp file to target
    fs::rename(&temp_path, path)
        .await
        .map_err(|e| SyncthingError::Io(e))?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[tokio::test]
    async fn test_native_filesystem_new() {
        let temp_dir = TempDir::new().unwrap();
        let fs = NativeFileSystem::new(temp_dir.path());
        assert_eq!(fs.root, temp_dir.path());
    }

    #[tokio::test]
    async fn test_create_dir_and_exists() {
        let temp_dir = TempDir::new().unwrap();
        let fs = NativeFileSystem::new(temp_dir.path());

        let test_dir = Path::new("test_subdir");
        assert!(!fs.exists(test_dir).await.unwrap());

        fs.create_dir(test_dir).await.unwrap();
        assert!(fs.exists(test_dir).await.unwrap());
    }

    #[tokio::test]
    async fn test_write_and_read_block() {
        let temp_dir = TempDir::new().unwrap();
        let fs = NativeFileSystem::new(temp_dir.path());

        let test_file = Path::new("test.txt");
        let data = b"Hello, World!";

        fs.write_block(test_file, 0, data).await.unwrap();

        let read_data = fs.read_block(test_file, 0, 100).await.unwrap();
        assert_eq!(read_data, data);
    }

    #[tokio::test]
    async fn test_write_block_at_offset() {
        let temp_dir = TempDir::new().unwrap();
        let fs = NativeFileSystem::new(temp_dir.path());

        let test_file = Path::new("test.txt");

        // Write first part
        fs.write_block(test_file, 0, b"Hello").await.unwrap();
        // Write second part at offset
        fs.write_block(test_file, 5, b" World").await.unwrap();

        let read_data = fs.read_block(test_file, 0, 100).await.unwrap();
        assert_eq!(read_data, b"Hello World");
    }

    #[tokio::test]
    async fn test_read_block_partial() {
        let temp_dir = TempDir::new().unwrap();
        let fs = NativeFileSystem::new(temp_dir.path());

        let test_file = Path::new("test.txt");
        fs.write_block(test_file, 0, b"Hello, World!").await.unwrap();

        let read_data = fs.read_block(test_file, 7, 5).await.unwrap();
        assert_eq!(read_data, b"World");
    }

    #[tokio::test]
    async fn test_file_info() {
        let temp_dir = TempDir::new().unwrap();
        let fs = NativeFileSystem::new(temp_dir.path());

        let test_file = Path::new("test.txt");
        let data = b"Test content for hashing";
        fs.write_block(test_file, 0, data).await.unwrap();

        let info = fs.file_info(test_file).await.unwrap();
        assert_eq!(info.name, "test.txt");
        assert_eq!(info.size, data.len() as i64);
        assert_eq!(info.file_type, FileType::File);
    }

    #[tokio::test]
    async fn test_remove() {
        let temp_dir = TempDir::new().unwrap();
        let fs = NativeFileSystem::new(temp_dir.path());

        let test_file = Path::new("to_delete.txt");
        fs.write_block(test_file, 0, b"delete me").await.unwrap();
        assert!(fs.exists(test_file).await.unwrap());

        fs.remove(test_file).await.unwrap();
        assert!(!fs.exists(test_file).await.unwrap());
    }

    #[tokio::test]
    async fn test_rename() {
        let temp_dir = TempDir::new().unwrap();
        let fs = NativeFileSystem::new(temp_dir.path());

        let from = Path::new("old_name.txt");
        let to = Path::new("new_name.txt");

        fs.write_block(from, 0, b"content").await.unwrap();
        fs.rename(from, to).await.unwrap();

        assert!(!fs.exists(from).await.unwrap());
        assert!(fs.exists(to).await.unwrap());

        let content = fs.read_block(to, 0, 100).await.unwrap();
        assert_eq!(content, b"content");
    }

    #[tokio::test]
    async fn test_scan_directory() {
        let temp_dir = TempDir::new().unwrap();
        let fs = NativeFileSystem::new(temp_dir.path());

        // Create some files and directories
        fs.create_dir(Path::new("subdir")).await.unwrap();
        fs.write_block(Path::new("file1.txt"), 0, b"content1")
            .await
            .unwrap();
        fs.write_block(Path::new("subdir/file2.txt"), 0, b"content2")
            .await
            .unwrap();

        let entries = fs.scan_directory(Path::new(".")).await.unwrap();
        assert_eq!(entries.len(), 3); // subdir, file1.txt, subdir/file2.txt

        let names: Vec<_> = entries.iter().map(|e| e.name.clone()).collect();
        assert!(names.contains(&"subdir".to_string()));
        assert!(names.contains(&"file1.txt".to_string()));
        assert!(names.contains(&"subdir/file2.txt".to_string()));
    }

    #[tokio::test]
    async fn test_scan_directory_with_ignore() {
        let temp_dir = TempDir::new().unwrap();
        let fs = NativeFileSystem::new(temp_dir.path());

        // Create some files and directories
        fs.create_dir(Path::new("ignored_dir")).await.unwrap();
        fs.create_dir(Path::new("kept_dir")).await.unwrap();
        fs.write_block(Path::new("ignored.txt"), 0, b"ignored")
            .await
            .unwrap();
        fs.write_block(Path::new("kept.txt"), 0, b"kept")
            .await
            .unwrap();
        fs.write_block(Path::new("ignored_dir/nested.txt"), 0, b"nested")
            .await
            .unwrap();
        fs.write_block(Path::new("kept_dir/nested.txt"), 0, b"nested")
            .await
            .unwrap();

        let mut patterns = IgnorePatterns::new();
        patterns.add_pattern("ignored_dir/").unwrap();
        patterns.add_pattern("ignored.txt").unwrap();

        let entries = fs
            .scan_directory_with_ignore(Path::new("."), &patterns)
            .await
            .unwrap();

        let names: Vec<_> = entries.iter().map(|e| e.name.clone()).collect();
        assert!(!names.contains(&"ignored_dir".to_string()));
        assert!(!names.contains(&"ignored_dir/nested.txt".to_string()));
        assert!(!names.contains(&"ignored.txt".to_string()));
        assert!(names.contains(&"kept_dir".to_string()));
        assert!(names.contains(&"kept_dir/nested.txt".to_string()));
        assert!(names.contains(&"kept.txt".to_string()));
    }

    #[tokio::test]
    async fn test_hash_file() {
        let temp_dir = TempDir::new().unwrap();
        let fs = NativeFileSystem::new(temp_dir.path());

        let test_file = Path::new("hash_me.txt");
        let data = b"data to hash";
        fs.write_block(test_file, 0, data).await.unwrap();

        let hashes = fs.hash_file(test_file).await.unwrap();
        assert_eq!(hashes.len(), 1);

        // Verify hash is correct
        let expected_hash = BlockHash::from_data(data);
        assert_eq!(hashes[0], expected_hash);
    }

    #[tokio::test]
    async fn test_atomic_write() {
        let temp_dir = TempDir::new().unwrap();
        let path = temp_dir.path().join("atomic.txt");

        atomic_write(&path, b"atomic content").await.unwrap();

        let content = fs::read_to_string(&path).await.unwrap();
        assert_eq!(content, "atomic content");
    }

    #[tokio::test]
    async fn test_nested_directory_creation() {
        let temp_dir = TempDir::new().unwrap();
        let fs = NativeFileSystem::new(temp_dir.path());

        let nested_file = Path::new("a/b/c/nested.txt");
        fs.write_block(nested_file, 0, b"nested content")
            .await
            .unwrap();

        let content = fs.read_block(nested_file, 0, 100).await.unwrap();
        assert_eq!(content, b"nested content");
    }
}
