//! .stignore file parser
//!
//! ⚠️ STATUS: UNVERIFIED - Agent-B Delivery
//! This code is generated by Agent-B and has NOT been verified by Master Agent.
//! DO NOT USE IN PRODUCTION.
//!
//! Parses .stignore files and provides pattern matching for
//! filtering files during synchronization.
//!
//! Supports standard ignore patterns similar to .gitignore:
//! - `*` matches any sequence of characters except `/`
//! - `?` matches any single character except `/`
//! - `**` matches any sequence of characters including `/`
//! - `!` negates a pattern
//! - `#` starts a comment
//! - `\` escapes special characters
//! - `(?i)` case-insensitive matching
//! - `(?d)` allow deleting ignored directories
//! - `#include` / `@include` include other ignore files

use std::collections::{HashMap, HashSet};
use std::path::{Path, PathBuf};
use syncthing_core::{Result, SyncthingError};

/// Cache for ignore pattern lookups
#[derive(Debug, Clone, Default)]
pub struct IgnoreCache {
    map: HashMap<PathBuf, bool>,
}

impl IgnoreCache {
    /// Create a new empty cache
    pub fn new() -> Self {
        Self {
            map: HashMap::new(),
        }
    }

    /// Get a cached result
    pub fn get(&self, path: &Path) -> Option<bool> {
        self.map.get(path).copied()
    }

    /// Set a cache entry
    pub fn set(&mut self, path: &Path, result: bool) {
        self.map.insert(path.to_path_buf(), result);
    }

    /// Clear all cache entries
    pub fn clear(&mut self) {
        self.map.clear();
    }
}

/// Pattern matcher for ignore rules
///
/// Holds a collection of patterns loaded from a .stignore file
/// and provides matching functionality.
#[derive(Debug, Clone, Default)]
pub struct IgnorePatterns {
    /// List of patterns in order of definition
    patterns: Vec<Pattern>,
    /// Whether to include patterns are present (for optimization)
    has_includes: bool,
    /// Include file paths recorded from #include / @include directives
    includes: Vec<PathBuf>,
    /// Cache for lookup results
    cache: Option<IgnoreCache>,
}

/// A single ignore pattern
#[derive(Debug, Clone)]
#[allow(dead_code)]
struct Pattern {
    /// The pattern string
    pattern: String,
    /// Whether this is an include pattern (starts with !)
    is_include: bool,
    /// Whether this pattern is a directory-only match (ends with /)
    is_directory: bool,
    /// Whether this pattern should match at root only (starts with /)
    is_root_only: bool,
    /// Whether this pattern is case-insensitive (prefixed with (?i))
    case_insensitive: bool,
    /// Whether this pattern allows deleting ignored directories (prefixed with (?d))
    allow_delete: bool,
    /// The compiled pattern for matching
    regex: regex::Regex,
}

impl IgnorePatterns {
    /// Create an empty ignore patterns collection
    pub fn new() -> Self {
        Self {
            patterns: Vec::new(),
            has_includes: false,
            includes: Vec::new(),
            cache: None,
        }
    }

    /// Load ignore patterns from a .stignore file
    ///
    /// Parses the file and compiles all patterns for efficient matching.
    /// Recursively loads any `#include` or `@include` directives.
    ///
    /// # Arguments
    /// * `path` - Path to the .stignore file
    ///
    /// # Returns
    /// An IgnorePatterns instance with all loaded patterns
    pub async fn from_file(path: &Path) -> Result<Self> {
        let content = tokio::fs::read_to_string(path)
            .await
            .map_err(SyncthingError::Io)?;

        let base_dir = path.parent().unwrap_or(Path::new(""));
        let mut loaded = HashSet::new();
        loaded.insert(path.to_path_buf());

        let mut patterns = Self::parse(&content);

        // Load includes recursively
        let includes = patterns.includes.clone();
        for include_path in includes {
            let resolved = if include_path.is_absolute() {
                include_path
            } else {
                base_dir.join(include_path)
            };
            Box::pin(Self::load_includes(resolved, &mut patterns, &mut loaded)).await?;
        }

        Ok(patterns)
    }

    /// Recursively load an included ignore file
    async fn load_includes(
        path: PathBuf,
        patterns: &mut IgnorePatterns,
        loaded: &mut HashSet<PathBuf>,
    ) -> Result<()> {
        if loaded.contains(&path) {
            // Cycle detected, skip
            return Ok(());
        }
        loaded.insert(path.clone());

        let content = tokio::fs::read_to_string(&path)
            .await
            .map_err(SyncthingError::Io)?;

        let base_dir = path.parent().unwrap_or(Path::new("")).to_path_buf();
        let included = Self::parse(&content);

        patterns.patterns.extend(included.patterns);
        if included.has_includes {
            patterns.has_includes = true;
        }

        for include_path in included.includes {
            let resolved = if include_path.is_absolute() {
                include_path
            } else {
                base_dir.join(include_path)
            };
            Box::pin(Self::load_includes(resolved, patterns, loaded)).await?;
        }

        Ok(())
    }

    /// Load ignore patterns from a string
    ///
    /// Useful for testing or when patterns come from sources
    /// other than a file.
    ///
    /// # Arguments
    /// * `content` - The ignore file content as a string
    pub fn parse(content: &str) -> Self {
        let mut patterns = Vec::new();
        let mut has_includes = false;
        let mut includes = Vec::new();

        for line in content.lines() {
            let trimmed = line.trim();

            // Skip empty lines and // comments
            if trimmed.is_empty() || trimmed.starts_with("//") {
                continue;
            }

            // Handle include directives
            if trimmed.starts_with("#include ") || trimmed.starts_with("@include ") {
                if let Some(file) = trimmed.split_once(' ').map(|x| x.1) {
                    let file = file.trim();
                    if !file.is_empty() {
                        includes.push(PathBuf::from(file));
                    }
                }
                continue;
            }

            // Skip # comments (but not includes, which are handled above)
            if trimmed.starts_with('#') {
                continue;
            }

            match Pattern::parse(trimmed) {
                Ok(pattern) => {
                    if pattern.is_include {
                        has_includes = true;
                    }
                    patterns.push(pattern);
                }
                Err(e) => {
                    // Log the error but continue processing other patterns
                    tracing::warn!("Failed to parse ignore pattern '{}': {}", trimmed, e);
                }
            }
        }

        Self {
            patterns,
            has_includes,
            includes,
            cache: None,
        }
    }

    /// Check if a path matches any ignore pattern
    ///
    /// Returns true if the path should be ignored according to the
    /// loaded patterns. Last matching pattern wins (for include patterns).
    ///
    /// # Arguments
    /// * `path` - The path to check (relative to the ignore file location)
    ///
    /// # Returns
    /// true if the path should be ignored, false otherwise
    pub fn is_ignored(&self, path: &Path) -> bool {
        let path_str = path.to_string_lossy();
        // Normalize path separators
        let path_str = path_str.replace('\\', "/");

        self.is_ignored_str(&path_str)
    }

    /// Check if a path matches any ignore pattern, with caching
    ///
    /// # Arguments
    /// * `path` - The path to check
    ///
    /// # Returns
    /// true if the path should be ignored, false otherwise
    pub fn is_ignored_cached(&mut self, path: &Path) -> bool {
        if let Some(ref cache) = self.cache {
            if let Some(result) = cache.get(path) {
                return result;
            }
        }

        let result = self.is_ignored(path);

        if self.cache.is_none() {
            self.cache = Some(IgnoreCache::new());
        }
        if let Some(ref mut cache) = self.cache {
            cache.set(path, result);
        }

        result
    }

    /// Clear the ignore cache
    pub fn clear_cache(&mut self) {
        if let Some(ref mut cache) = self.cache {
            cache.clear();
        }
    }

    /// Check if a path string matches any ignore pattern
    fn is_ignored_str(&self, path_str: &str) -> bool {
        if self.patterns.is_empty() {
            return false;
        }

        let mut ignored = false;

        for pattern in &self.patterns {
            if pattern.matches(path_str) {
                if pattern.is_include {
                    // This pattern un-ignores (includes) the path
                    ignored = false;
                } else {
                    // This pattern ignores the path
                    ignored = true;
                }
            }
        }

        ignored
    }

    /// Check if a path is explicitly included
    ///
    /// Returns true only if the path matches an include pattern (!).
    pub fn is_included(&self, path: &Path) -> bool {
        if !self.has_includes {
            return false;
        }

        let path_str = path.to_string_lossy();
        let path_str = path_str.replace('\\', "/");

        self.patterns
            .iter()
            .any(|p| p.is_include && p.matches(&path_str))
    }

    /// Get the number of patterns
    pub fn len(&self) -> usize {
        self.patterns.len()
    }

    /// Check if there are no patterns
    pub fn is_empty(&self) -> bool {
        self.patterns.is_empty()
    }

    /// Add a pattern programmatically
    pub fn add_pattern(&mut self, pattern: &str) -> Result<()> {
        let pattern = Pattern::parse(pattern)?;
        if pattern.is_include {
            self.has_includes = true;
        }
        self.patterns.push(pattern);
        Ok(())
    }

    /// Determine whether ignored directories can be safely skipped during scanning
    ///
    /// Returns true only if there are no include patterns (`!`) and no
    /// `allow_delete` patterns, meaning we can prune ignored directories.
    pub fn allows_skipping_ignored_dirs(&self) -> bool {
        !self.patterns.iter().any(|p| p.is_include || p.allow_delete)
    }
}

impl Pattern {
    /// Parse a pattern string
    fn parse(pattern: &str) -> Result<Self> {
        let mut line = pattern;

        // Parse prefixes: !, (?i), (?d) in any order, each at most once
        let mut is_include = false;
        let mut case_insensitive = false;
        let mut allow_delete = false;
        let mut seen = [false; 3];

        loop {
            if line.starts_with('!') && !seen[0] {
                seen[0] = true;
                is_include = true;
                line = &line[1..];
            } else if line.starts_with("(?i)") && !seen[1] {
                seen[1] = true;
                case_insensitive = true;
                line = &line[4..];
            } else if line.starts_with("(?d)") && !seen[2] {
                seen[2] = true;
                allow_delete = true;
                line = &line[4..];
            } else {
                break;
            }
        }

        if line.is_empty() {
            return Err(SyncthingError::config("missing pattern".to_string()));
        }

        let mut chars = line.chars().peekable();

        // Check for root-only prefix
        let is_root_only = chars.peek() == Some(&'/');
        if is_root_only {
            chars.next(); // consume '/'
        }

        // Build the pattern string
        let mut pattern_str = String::new();
        while let Some(ch) = chars.next() {
            match ch {
                '\\' => {
                    // Escape next character
                    if let Some(next) = chars.next() {
                        pattern_str.push(next);
                    }
                }
                _ => pattern_str.push(ch),
            }
        }

        // Check for directory suffix
        let is_directory = pattern_str.ends_with('/');
        if is_directory {
            pattern_str.pop(); // Remove trailing /
        }

        // Compile to regex
        let regex = Self::compile_regex(&pattern_str, is_root_only, is_directory, case_insensitive)?;

        Ok(Self {
            pattern: pattern_str,
            is_include,
            is_directory,
            is_root_only,
            case_insensitive,
            allow_delete,
            regex,
        })
    }

    /// Convert a glob pattern to a regex
    fn compile_regex(
        pattern: &str,
        is_root_only: bool,
        is_directory: bool,
        case_insensitive: bool,
    ) -> Result<regex::Regex> {
        let mut regex_str = String::new();

        if case_insensitive {
            regex_str.push_str("(?i)");
        }

        regex_str.push('^');

        if !is_root_only {
            // Non-root-only patterns can match at any directory level
            regex_str.push_str("(?:.*/)?");
        }

        let mut chars = pattern.chars().peekable();
        while let Some(ch) = chars.next() {
            match ch {
                '*' => {
                    if chars.peek() == Some(&'*') {
                        // ** matches any sequence including /
                        chars.next(); // consume second *
                        if chars.peek() == Some(&'/') {
                            chars.next(); // consume /
                            regex_str.push_str("(?:.*/)?");
                        } else {
                            regex_str.push_str(".*");
                        }
                    } else {
                        // * matches any sequence except /
                        regex_str.push_str("[^/]*");
                    }
                }
                '?' => {
                    // ? matches any single character except /
                    regex_str.push_str("[^/]");
                }
                '.' => {
                    regex_str.push_str("\\.");
                }
                '+' | '(' | ')' | '|' | '^' | '$' | '{' | '}' | '[' | ']' => {
                    regex_str.push('\\');
                    regex_str.push(ch);
                }
                _ => regex_str.push(ch),
            }
        }

        if is_directory {
            regex_str.push_str("(?:/.*)?");
        }

        regex_str.push('$');

        regex::Regex::new(&regex_str).map_err(|e| {
            SyncthingError::config(format!("Invalid pattern '{}': {}", pattern, e))
        })
    }

    /// Check if this pattern matches a path
    fn matches(&self, path: &str) -> bool {
        self.regex.is_match(path)
    }
}

/// Default ignore patterns for Syncthing
///
/// Returns a set of common patterns that should be ignored
/// in most Syncthing deployments.
pub fn default_ignore_patterns() -> IgnorePatterns {
    let patterns = r#"
# Syncthing's own files
.stfolder
.stignore
.stversions

# OS generated files
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db
desktop.ini

# Editor backup files
*~
*.swp
*.swo
*.bak
*.orig

# Temporary files
*.tmp
*.temp
*.part
*.crdownload
"#;

    IgnorePatterns::parse(patterns)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use tempfile::NamedTempFile;

    #[test]
    fn test_empty_patterns() {
        let patterns = IgnorePatterns::new();
        assert!(!patterns.is_ignored(Path::new("anything.txt")));
    }

    #[test]
    fn test_simple_pattern() {
        let mut patterns = IgnorePatterns::new();
        patterns.add_pattern("*.txt").unwrap();

        assert!(patterns.is_ignored(Path::new("file.txt")));
        assert!(patterns.is_ignored(Path::new("dir/file.txt")));
        assert!(!patterns.is_ignored(Path::new("file.doc")));
    }

    #[test]
    fn test_directory_pattern() {
        let mut patterns = IgnorePatterns::new();
        patterns.add_pattern("build/").unwrap();

        assert!(patterns.is_ignored(Path::new("build")));
        assert!(patterns.is_ignored(Path::new("build/output")));
        assert!(!patterns.is_ignored(Path::new("build.txt")));
    }

    #[test]
    fn test_include_pattern() {
        let mut patterns = IgnorePatterns::new();
        patterns.add_pattern("*.txt").unwrap();
        patterns.add_pattern("!important.txt").unwrap();

        assert!(patterns.is_ignored(Path::new("file.txt")));
        assert!(!patterns.is_ignored(Path::new("important.txt")));
    }

    #[test]
    fn test_root_only_pattern() {
        let mut patterns = IgnorePatterns::new();
        patterns.add_pattern("/root.txt").unwrap();

        assert!(patterns.is_ignored(Path::new("root.txt")));
        assert!(!patterns.is_ignored(Path::new("subdir/root.txt")));
    }

    #[test]
    fn test_double_star_pattern() {
        let mut patterns = IgnorePatterns::new();
        patterns.add_pattern("**/temp").unwrap();

        assert!(patterns.is_ignored(Path::new("temp")));
        assert!(patterns.is_ignored(Path::new("a/temp")));
        assert!(patterns.is_ignored(Path::new("a/b/temp")));
    }

    #[test]
    fn test_question_mark_pattern() {
        let mut patterns = IgnorePatterns::new();
        patterns.add_pattern("file?.txt").unwrap();

        assert!(patterns.is_ignored(Path::new("file1.txt")));
        assert!(patterns.is_ignored(Path::new("fileA.txt")));
        assert!(!patterns.is_ignored(Path::new("file12.txt")));
    }

    #[test]
    fn test_from_string() {
        let content = r#"
# This is a comment
*.log
build/
!important.log
"#;

        let patterns = IgnorePatterns::parse(content);

        assert!(patterns.is_ignored(Path::new("debug.log")));
        assert!(patterns.is_ignored(Path::new("build")));
        assert!(!patterns.is_ignored(Path::new("important.log")));
    }

    #[tokio::test]
    async fn test_from_file() {
        let mut temp_file = NamedTempFile::new().unwrap();
        writeln!(temp_file, "*.tmp").unwrap();
        writeln!(temp_file, "temp/").unwrap();

        let patterns = IgnorePatterns::from_file(temp_file.path()).await.unwrap();

        assert!(patterns.is_ignored(Path::new("file.tmp")));
        assert!(patterns.is_ignored(Path::new("temp")));
    }

    #[test]
    fn test_default_patterns() {
        let patterns = default_ignore_patterns();

        assert!(patterns.is_ignored(Path::new(".stfolder")));
        assert!(patterns.is_ignored(Path::new(".stignore")));
        assert!(patterns.is_ignored(Path::new(".DS_Store")));
        assert!(patterns.is_ignored(Path::new("Thumbs.db")));
    }

    #[test]
    fn test_windows_paths() {
        let mut patterns = IgnorePatterns::new();
        patterns.add_pattern("*.txt").unwrap();

        // Windows path separators should be normalized
        assert!(patterns.is_ignored(Path::new("dir\\file.txt")));
    }

    #[test]
    fn test_last_match_wins() {
        let mut patterns = IgnorePatterns::new();
        patterns.add_pattern("*.txt").unwrap();
        patterns.add_pattern("!keep.txt").unwrap();
        patterns.add_pattern("keep.txt").unwrap(); // This re-ignores it

        assert!(patterns.is_ignored(Path::new("keep.txt")));
    }

    #[test]
    fn test_escaped_characters() {
        let mut patterns = IgnorePatterns::new();
        // Note: backslash escaping is handled in pattern parsing
        patterns.add_pattern("file\\.txt").unwrap();

        assert!(patterns.is_ignored(Path::new("file.txt")));
    }

    #[test]
    fn test_is_included() {
        let mut patterns = IgnorePatterns::new();
        patterns.add_pattern("*.txt").unwrap();
        patterns.add_pattern("!special.txt").unwrap();

        assert!(patterns.is_included(Path::new("special.txt")));
        assert!(!patterns.is_included(Path::new("other.txt")));
    }

    #[test]
    fn test_pattern_count() {
        let mut patterns = IgnorePatterns::new();
        assert_eq!(patterns.len(), 0);
        assert!(patterns.is_empty());

        patterns.add_pattern("*.txt").unwrap();
        assert_eq!(patterns.len(), 1);
        assert!(!patterns.is_empty());
    }

    #[test]
    fn test_case_insensitive_pattern() {
        let mut patterns = IgnorePatterns::new();
        patterns.add_pattern("(?i)*.TXT").unwrap();

        assert!(patterns.is_ignored(Path::new("file.txt")));
        assert!(patterns.is_ignored(Path::new("file.TXT")));
        assert!(patterns.is_ignored(Path::new("file.Txt")));
        assert!(!patterns.is_ignored(Path::new("file.doc")));
    }

    #[test]
    fn test_case_insensitive_prefix_order() {
        let mut patterns = IgnorePatterns::new();
        patterns.add_pattern("*.txt").unwrap();
        patterns.add_pattern("!(?i)KEEP.txt").unwrap();

        assert!(patterns.is_ignored(Path::new("other.txt")));
        assert!(!patterns.is_ignored(Path::new("keep.txt")));
        assert!(!patterns.is_ignored(Path::new("KEEP.TXT")));
    }

    #[test]
    fn test_allow_delete_pattern() {
        let mut patterns = IgnorePatterns::new();
        patterns.add_pattern("(?d)temp/").unwrap();

        assert!(patterns.is_ignored(Path::new("temp")));
        assert!(!patterns.allows_skipping_ignored_dirs());
    }

    #[test]
    fn test_combined_prefixes() {
        let mut patterns = IgnorePatterns::new();
        patterns.add_pattern("(?i)(?d)secret").unwrap();

        assert!(patterns.is_ignored(Path::new("SECRET")));
        assert!(patterns.is_ignored(Path::new("secret")));
        assert!(!patterns.allows_skipping_ignored_dirs());
    }

    #[tokio::test]
    async fn test_include_recursive() {
        let temp_dir = tempfile::TempDir::new().unwrap();
        let root = temp_dir.path();

        let main_path = root.join(".stignore");
        tokio::fs::write(&main_path, "*.log\n#include sub.ignore\n")
            .await
            .unwrap();

        let sub_path = root.join("sub.ignore");
        tokio::fs::write(&sub_path, "*.tmp\n").await.unwrap();

        let patterns = IgnorePatterns::from_file(&main_path).await.unwrap();

        assert!(patterns.is_ignored(Path::new("debug.log")));
        assert!(patterns.is_ignored(Path::new("file.tmp")));
        assert!(!patterns.is_ignored(Path::new("file.txt")));
    }

    #[tokio::test]
    async fn test_at_include() {
        let temp_dir = tempfile::TempDir::new().unwrap();
        let root = temp_dir.path();

        let main_path = root.join(".stignore");
        tokio::fs::write(&main_path, "*.log\n@include other.ignore\n")
            .await
            .unwrap();

        let other_path = root.join("other.ignore");
        tokio::fs::write(&other_path, "*.bak\n").await.unwrap();

        let patterns = IgnorePatterns::from_file(&main_path).await.unwrap();

        assert!(patterns.is_ignored(Path::new("debug.log")));
        assert!(patterns.is_ignored(Path::new("file.bak")));
    }

    #[tokio::test]
    async fn test_include_cycle_detection() {
        let temp_dir = tempfile::TempDir::new().unwrap();
        let root = temp_dir.path();

        let main_path = root.join(".stignore");
        tokio::fs::write(&main_path, "*.log\n#include a.ignore\n")
            .await
            .unwrap();

        let a_path = root.join("a.ignore");
        tokio::fs::write(&a_path, "*.tmp\n#include b.ignore\n")
            .await
            .unwrap();

        let b_path = root.join("b.ignore");
        tokio::fs::write(&b_path, "*.bak\n#include a.ignore\n")
            .await
            .unwrap();

        let patterns = IgnorePatterns::from_file(&main_path).await.unwrap();

        // Should not infinite loop; patterns from a and b should be loaded once
        assert!(patterns.is_ignored(Path::new("debug.log")));
        assert!(patterns.is_ignored(Path::new("file.tmp")));
        assert!(patterns.is_ignored(Path::new("file.bak")));
    }

    #[test]
    fn test_cache_hit_and_invalidation() {
        let mut patterns = IgnorePatterns::new();
        patterns.add_pattern("*.txt").unwrap();

        // First calls populate cache
        assert!(patterns.is_ignored_cached(Path::new("file.txt")));
        assert!(!patterns.is_ignored_cached(Path::new("file.doc")));

        // Clear cache
        patterns.clear_cache();

        // Should still work after clearing
        assert!(patterns.is_ignored_cached(Path::new("file.txt")));
        assert!(!patterns.is_ignored_cached(Path::new("file.doc")));
    }

    #[test]
    fn test_allows_skipping_ignored_dirs() {
        let mut patterns = IgnorePatterns::new();
        patterns.add_pattern("*.txt").unwrap();
        assert!(patterns.allows_skipping_ignored_dirs());

        let mut patterns = IgnorePatterns::new();
        patterns.add_pattern("!important.txt").unwrap();
        assert!(!patterns.allows_skipping_ignored_dirs());

        let mut patterns = IgnorePatterns::new();
        patterns.add_pattern("(?d)temp/").unwrap();
        assert!(!patterns.allows_skipping_ignored_dirs());
    }
}
