//! Filesystem Abstraction for Syncthing
//!
//! ⚠️ STATUS: UNVERIFIED - Agent-B Delivery
//! This code is generated by Agent-B and has NOT been verified by Master Agent.
//! DO NOT USE IN PRODUCTION.
//!
//! Module: syncthing-fs
//! Worker: Agent-B
//! Commit: PENDING
//! Timestamp: PENDING
//!
//! This crate provides filesystem abstraction and monitoring capabilities
//! for the Syncthing Rust implementation. It includes:
//!
//! - `NativeFileSystem`: Cross-platform FileSystem trait implementation
//! - `FolderWatcher`: Filesystem change monitoring using notify
//! - `scan_file`: Block-level file scanning with SHA-256 hashing
//! - `IgnorePatterns`: .stignore file parsing and pattern matching
//!
//! # Platform Support
//!
//! - Windows (via native APIs)
//! - macOS (via FSEvents through notify)
//! - Linux (via inotify through notify)
//!
//! # Example
//!
//! ```rust,no_run
//! use syncthing_fs::NativeFileSystem;
//! use syncthing_core::traits::FileSystem;
//! use std::path::Path;
//!
//! # async fn example() -> syncthing_core::Result<()> {
//! let fs = NativeFileSystem::new("/path/to/folder");
//!
//! // Write data to a file
//! fs.write_block(Path::new("test.txt"), 0, b"Hello, World!").await?;
//!
//! // Read data back
//! let data = fs.read_block(Path::new("test.txt"), 0, 100).await?;
//! # Ok(())
//! # }
//! ```

#![warn(missing_docs)]
#![warn(rust_2018_idioms)]

pub mod filesystem;
pub mod ignore;
pub mod scanner;
pub mod watcher;

// Re-export main types for convenience
pub use filesystem::{atomic_write, NativeFileSystem};
pub use ignore::{default_ignore_patterns, IgnorePatterns};
pub use scanner::{hash_block, optimal_block_size, quick_scan, scan_directory, scan_file, verify_file};
pub use watcher::{create_buffer_watcher, EventCollector, FolderWatcher, FsEvent};

/// Default block size for file operations (128 KB)
pub const DEFAULT_BLOCK_SIZE: usize = 128 * 1024;

/// Minimum block size (4 KB)
pub const MIN_BLOCK_SIZE: usize = 4 * 1024;

/// Maximum block size (16 MB)
pub const MAX_BLOCK_SIZE: usize = 16 * 1024 * 1024;



/// Utility function to check if a file should be ignored
///
/// Combines ignore patterns to determine if a file should be
/// excluded from synchronization.
///
/// # Arguments
/// * `path` - The file path to check
/// * `patterns` - The ignore patterns to apply
///
/// # Returns
/// true if the file should be ignored
pub fn should_ignore(path: &std::path::Path, patterns: &IgnorePatterns) -> bool {
    patterns.is_ignored(path)
}

/// Utility function to get file extension
///
/// Returns the extension of a file path as a string slice.
pub fn get_extension(path: &std::path::Path) -> Option<&str> {
    path.extension().and_then(|e| e.to_str())
}

/// Check if a path is a temporary file
///
/// Returns true if the file has a common temporary file extension.
pub fn is_temporary_file(path: &std::path::Path) -> bool {
    match get_extension(path) {
        Some("tmp") | Some("temp") | Some("part") | Some("crdownload") => true,
        _ => {
            // Check for common temp file patterns
            let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
            name.ends_with('~') || name.starts_with('~') || name.starts_with(".~")
        }
    }
}

/// Calculate the number of blocks needed for a file
///
/// # Arguments
/// * `file_size` - The size of the file in bytes
/// * `block_size` - The size of each block
///
/// # Returns
/// The number of blocks needed
pub fn calculate_block_count(file_size: u64, block_size: usize) -> usize {
    if file_size == 0 {
        return 0;
    }
    file_size.div_ceil(block_size as u64) as usize
}

/// Get the offset and size for a specific block
///
/// # Arguments
/// * `block_index` - The index of the block
/// * `block_size` - The size of each block
/// * `file_size` - The total file size
///
/// # Returns
/// A tuple of (offset, size) for the block
pub fn get_block_info(block_index: usize, block_size: usize, file_size: u64) -> (u64, usize) {
    let offset = block_index as u64 * block_size as u64;
    let size = if offset + block_size as u64 > file_size {
        (file_size - offset) as usize
    } else {
        block_size
    };
    (offset, size)
}

/// Sanitize a filename for cross-platform compatibility
///
/// Removes or replaces characters that are invalid on some platforms.
pub fn sanitize_filename(name: &str) -> String {
    let invalid_chars: &[char] = &['<', '>', ':', '"', '|', '?', '*'];
    name.chars()
        .map(|c| if invalid_chars.contains(&c) { '_' } else { c })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    #[test]
    fn test_default_block_size() {
        assert_eq!(DEFAULT_BLOCK_SIZE, 128 * 1024);
    }

    #[test]
    fn test_get_extension() {
        assert_eq!(get_extension(Path::new("file.txt")), Some("txt"));
        assert_eq!(get_extension(Path::new("file.tar.gz")), Some("gz"));
        assert_eq!(get_extension(Path::new("no_extension")), None);
    }

    #[test]
    fn test_is_temporary_file() {
        assert!(is_temporary_file(Path::new("file.tmp")));
        assert!(is_temporary_file(Path::new("file.part")));
        assert!(is_temporary_file(Path::new("file~")));
        assert!(is_temporary_file(Path::new("~backup")));
        assert!(!is_temporary_file(Path::new("file.txt")));
    }

    #[test]
    fn test_calculate_block_count() {
        assert_eq!(calculate_block_count(0, 1024), 0);
        assert_eq!(calculate_block_count(100, 1024), 1);
        assert_eq!(calculate_block_count(1024, 1024), 1);
        assert_eq!(calculate_block_count(1025, 1024), 2);
        assert_eq!(calculate_block_count(2048, 1024), 2);
    }

    #[test]
    fn test_get_block_info() {
        assert_eq!(get_block_info(0, 1024, 500), (0, 500));
        assert_eq!(get_block_info(0, 1024, 1024), (0, 1024));
        assert_eq!(get_block_info(1, 1024, 1500), (1024, 476));
    }

    #[test]
    fn test_sanitize_filename() {
        assert_eq!(sanitize_filename("file:name.txt"), "file_name.txt");
        assert_eq!(sanitize_filename("file|name"), "file_name");
        assert_eq!(sanitize_filename("normal.txt"), "normal.txt");
    }

    #[test]
    fn test_should_ignore() {
        let mut patterns = IgnorePatterns::new();
        patterns.add_pattern("*.log").unwrap();

        assert!(should_ignore(Path::new("debug.log"), &patterns));
        assert!(!should_ignore(Path::new("file.txt"), &patterns));
    }
}
