//! File scanner with block hashing
//!
//! ⚠️ STATUS: UNVERIFIED - Agent-B Delivery
//! This code is generated by Agent-B and has NOT been verified by Master Agent.
//! DO NOT USE IN PRODUCTION.
//!
//! Provides file scanning capabilities with SHA-256 block hashing for
//! detecting file changes and content deduplication.

use std::path::Path;
use std::time::SystemTime;

use syncthing_core::{BlockHash, BlockInfo, FileInfo, FileType, Result, SyncthingError};
use tokio::fs::File;
use tokio::io::AsyncReadExt;

use crate::ignore::IgnorePatterns;

/// Default block size for file hashing (128 KB)
#[allow(dead_code)]
const DEFAULT_BLOCK_SIZE: usize = 128 * 1024;

/// Maximum block size (16 MB)
const MAX_BLOCK_SIZE: usize = 16 * 1024 * 1024;

/// Minimum block size (4 KB)
const MIN_BLOCK_SIZE: usize = 4 * 1024;

/// Scan a file and compute block hashes
///
/// Reads the file and divides it into blocks of the specified size,
/// computing a SHA-256 hash for each block.
///
/// # Arguments
/// * `path` - Path to the file to scan
/// * `block_size` - Size of each block in bytes
///
/// # Returns
/// FileInfo with complete block information
///
/// # Example
/// ```
/// use syncthing_fs::scanner::scan_file;
/// use std::path::Path;
///
/// # async fn example() -> syncthing_core::Result<()> {
/// let info = scan_file(Path::new("/path/to/file"), 128 * 1024).await?;
/// println!("File has {} blocks", info.blocks.len());
/// # Ok(())
/// # }
/// ```
pub async fn scan_file(path: &Path, block_size: usize) -> Result<FileInfo> {
    // Validate block size
    let block_size = block_size.clamp(MIN_BLOCK_SIZE, MAX_BLOCK_SIZE);

    // Get file metadata
    let metadata = tokio::fs::metadata(path).await.map_err(|e| SyncthingError::Io(e))?;

    if !metadata.is_file() {
        return Err(SyncthingError::io(format!(
            "Path is not a file: {}",
            path.display()
        )));
    }

    let file_name = path
        .file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_default();

    let mut info = FileInfo::new(&file_name);
    info.size = metadata.len() as i64;
    let duration = metadata
        .modified()
        .unwrap_or_else(|_| SystemTime::UNIX_EPOCH)
        .duration_since(SystemTime::UNIX_EPOCH)
        .unwrap_or_default();
    info.modified_s = duration.as_secs() as i64;
    info.modified_ns = duration.subsec_nanos() as i32;
    info.file_type = FileType::File;

    // Compute block hashes
    info.blocks = compute_block_hashes(path, block_size).await?;

    Ok(info)
}

/// Compute block hashes for a file
///
/// Reads the file in chunks and computes SHA-256 hashes for each block.
async fn compute_block_hashes(path: &Path, block_size: usize) -> Result<Vec<BlockInfo>> {
    let mut file = File::open(path).await.map_err(|e| SyncthingError::Io(e))?;
    let metadata = file.metadata().await.map_err(|e| SyncthingError::Io(e))?;
    let file_size = metadata.len();

    let mut blocks = Vec::new();
    let mut offset: u64 = 0;
    let mut buffer = vec![0u8; block_size];

    while offset < file_size {
        let bytes_read = file.read(&mut buffer).await.map_err(|e| SyncthingError::Io(e))?;
        if bytes_read == 0 {
            break;
        }

        let hash = hash_block(&buffer[..bytes_read]);
        blocks.push(BlockInfo {
            hash: hash.to_vec(),
            offset: offset as i64,
            size: bytes_read as i32,
        });

        offset += bytes_read as u64;
    }

    Ok(blocks)
}

/// Compute SHA-256 hash for a data block
///
/// # Arguments
/// * `data` - The data to hash
///
/// # Returns
/// The SHA-256 hash of the data as a BlockHash
///
/// # Example
/// ```
/// use syncthing_fs::scanner::hash_block;
///
/// let data = b"hello world";
/// let hash = hash_block(data);
/// ```
pub fn hash_block(data: &[u8]) -> BlockHash {
    BlockHash::from_data(data)
}

/// Calculate optimal block size based on file size
///
/// Returns a block size that provides good granularity while
/// keeping the number of blocks reasonable for large files.
///
/// # Arguments
/// * `file_size` - The size of the file in bytes
///
/// # Returns
/// Recommended block size in bytes
pub fn optimal_block_size(file_size: u64) -> usize {
    if file_size < 1024 * 1024 {
        // Files under 1MB: 4KB blocks
        4 * 1024
    } else if file_size < 100 * 1024 * 1024 {
        // Files 1MB-100MB: 128KB blocks
        128 * 1024
    } else if file_size < 1024 * 1024 * 1024 {
        // Files 100MB-1GB: 256KB blocks
        256 * 1024
    } else {
        // Files over 1GB: 1MB blocks
        1024 * 1024
    }
}

/// Quick scan that only computes metadata without full hashing
///
/// This is faster for detecting file changes when comparing
/// modification times and sizes is sufficient.
pub async fn quick_scan(path: &Path) -> Result<FileInfo> {
    let metadata = tokio::fs::metadata(path).await.map_err(|e| SyncthingError::Io(e))?;

    let file_name = path
        .file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_default();

    let mut info = FileInfo::new(&file_name);
    info.size = metadata.len() as i64;
    let duration = metadata
        .modified()
        .unwrap_or_else(|_| SystemTime::UNIX_EPOCH)
        .duration_since(SystemTime::UNIX_EPOCH)
        .unwrap_or_default();
    info.modified_s = duration.as_secs() as i64;
    info.modified_ns = duration.subsec_nanos() as i32;

    if metadata.file_type().is_symlink() {
        info.file_type = FileType::Symlink;
    } else if metadata.is_dir() {
        info.file_type = FileType::Directory;
    } else {
        info.file_type = FileType::File;
    }

    // Don't compute block hashes for quick scan
    info.blocks = Vec::new();

    Ok(info)
}

/// Scan a directory and return info for all entries
///
/// Recursively scans the directory and returns FileInfo for all
/// files, directories, and symlinks found.
///
/// # Arguments
/// * `path` - Path to the directory to scan
/// * `ignore_patterns` - Optional ignore patterns to filter entries
pub async fn scan_directory(
    path: &Path,
    ignore_patterns: Option<&IgnorePatterns>,
) -> Result<Vec<FileInfo>> {
    let path = path.to_path_buf();
    let ignore = ignore_patterns.map(|i| i.clone());

    // Collect entries in a blocking task to avoid blocking the async runtime
    let entries = tokio::task::spawn_blocking(move || {
        let metadata = std::fs::metadata(&path).map_err(|e| SyncthingError::Io(e))?;

        if !metadata.is_dir() {
            return Err(SyncthingError::io(format!(
                "Path is not a directory: {}",
                path.display()
            )));
        }

        let can_skip = ignore.as_ref().map(|i| i.allows_skipping_ignored_dirs()).unwrap_or(false);

        let mut results = Vec::new();
        let mut walker = walkdir::WalkDir::new(&path)
            .follow_links(false)
            .into_iter();

        while let Some(entry) = walker.next() {
            let entry = match entry {
                Ok(e) => e,
                Err(e) => return Err(SyncthingError::io(e.to_string())),
            };

            let entry_path = entry.path();

            // Skip the root directory itself
            if entry_path == path.as_path() {
                continue;
            }

            let rel_path = match entry_path.strip_prefix(&path) {
                Ok(p) => p,
                Err(_) => continue,
            };
            // Normalize path separators for cross-platform consistency
            let rel_path_str = rel_path.to_string_lossy().replace('\\', "/");

            // Check ignore patterns
            if let Some(ref ign) = ignore {
                let is_ignored = ign.is_ignored(Path::new(&rel_path_str));
                if entry.file_type().is_dir() {
                    if is_ignored {
                        if can_skip {
                            // Safe to prune this directory entirely
                            walker.skip_current_dir();
                        }
                        // Don't add ignored directory to results,
                        // even if we can't skip (children may still be included via !)
                        continue;
                    }
                } else if is_ignored {
                    continue;
                }
            }

            let is_file = entry.file_type().is_file();
            results.push((entry_path.to_path_buf(), rel_path_str, is_file));
        }

        Ok::<_, SyncthingError>(results)
    })
    .await
    .map_err(|e| SyncthingError::io(e.to_string()))?;

    let entries = entries?;

    let mut results = Vec::new();
    for (entry_path, rel_path_str, is_file) in entries {
        let info = if is_file {
            let block_size = optimal_block_size(
                std::fs::metadata(&entry_path).map(|m| m.len()).unwrap_or(0),
            );
            scan_file(&entry_path, block_size).await?
        } else {
            quick_scan(&entry_path).await?
        };

        // Override the name with the relative path
        let mut info_with_path = info;
        info_with_path.name = rel_path_str;
        results.push(info_with_path);
    }

    Ok(results)
}

/// Verify file integrity by comparing block hashes
///
/// Recomputes hashes for the file and compares them against
/// the expected hashes.
///
/// # Arguments
/// * `path` - Path to the file to verify
/// * `expected_hashes` - The expected block hashes
/// * `block_size` - Size of each block in bytes
///
/// # Returns
/// `Ok(())` if all hashes match, or an error if they don't
pub async fn verify_file(
    path: &Path,
    expected_hashes: &[BlockHash],
    block_size: usize,
) -> Result<()> {
    let info = scan_file(path, block_size).await?;

    let actual_hashes: Vec<_> = info.blocks.iter().map(|b| b.hash.clone()).collect();

    if actual_hashes.len() != expected_hashes.len() {
        return Err(SyncthingError::protocol(format!(
            "Block count mismatch: expected {}, got {}",
            expected_hashes.len(),
            actual_hashes.len()
        )));
    }

    for (i, (expected, actual)) in expected_hashes.iter().zip(actual_hashes.iter()).enumerate() {
        if expected.to_vec() != *actual {
            return Err(SyncthingError::protocol(format!(
                "Block {} hash mismatch",
                i
            )));
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;
    use tokio::fs;

    #[tokio::test]
    async fn test_scan_file() {
        let temp_dir = TempDir::new().unwrap();
        let file_path = temp_dir.path().join("test.txt");

        let content = b"Hello, World!";
        fs::write(&file_path, content).await.unwrap();

        let info = scan_file(&file_path, DEFAULT_BLOCK_SIZE).await.unwrap();

        assert_eq!(info.name, "test.txt");
        assert_eq!(info.size, content.len() as i64);
        assert_eq!(info.file_type, FileType::File);
        assert_eq!(info.blocks.len(), 1);

        // Verify the hash
        let expected_hash = hash_block(content);
        let actual_hash_bytes: [u8; 32] = info.blocks[0].hash.as_slice().try_into().unwrap();
        assert_eq!(BlockHash::from_bytes(actual_hash_bytes), expected_hash);
        assert_eq!(info.blocks[0].offset, 0);
        assert_eq!(info.blocks[0].size, content.len() as i32);
    }

    #[tokio::test]
    async fn test_scan_large_file() {
        let temp_dir = TempDir::new().unwrap();
        let file_path = temp_dir.path().join("large.bin");

        // Create a file larger than the block size
        // Use MIN_BLOCK_SIZE (4KB) as minimum to avoid clamping
        let block_size = MIN_BLOCK_SIZE;
        let content = vec![0u8; block_size * 3 + 100]; // 3 full blocks + partial
        fs::write(&file_path, &content).await.unwrap();

        let info = scan_file(&file_path, block_size).await.unwrap();

        assert_eq!(info.blocks.len(), 4); // 3 full + 1 partial
        assert_eq!(info.blocks[0].size, block_size as i32);
        assert_eq!(info.blocks[1].size, block_size as i32);
        assert_eq!(info.blocks[2].size, block_size as i32);
        assert_eq!(info.blocks[3].size, 100);
    }

    #[tokio::test]
    async fn test_hash_block() {
        let data1 = b"test data";
        let data2 = b"test data";
        let data3 = b"different data";

        let hash1 = hash_block(data1);
        let hash2 = hash_block(data2);
        let hash3 = hash_block(data3);

        assert_eq!(hash1, hash2); // Same data = same hash
        assert_ne!(hash1, hash3); // Different data = different hash
    }

    #[tokio::test]
    async fn test_optimal_block_size() {
        assert_eq!(optimal_block_size(1024), 4 * 1024); // Small file
        assert_eq!(optimal_block_size(50 * 1024 * 1024), 128 * 1024); // 50MB
        assert_eq!(optimal_block_size(500 * 1024 * 1024), 256 * 1024); // 500MB
        assert_eq!(optimal_block_size(2 * 1024 * 1024 * 1024), 1024 * 1024); // 2GB
    }

    #[tokio::test]
    async fn test_quick_scan() {
        let temp_dir = TempDir::new().unwrap();
        let file_path = temp_dir.path().join("quick.txt");

        fs::write(&file_path, b"content").await.unwrap();

        let info = quick_scan(&file_path).await.unwrap();

        assert_eq!(info.name, "quick.txt");
        assert_eq!(info.size, 7);
        assert!(info.blocks.is_empty()); // No hashes computed
    }

    #[tokio::test]
    async fn test_scan_directory() {
        let temp_dir = TempDir::new().unwrap();
        let root = temp_dir.path();

        // Create test structure
        fs::create_dir(root.join("subdir")).await.unwrap();
        fs::write(root.join("file1.txt"), b"content1").await.unwrap();
        fs::write(root.join("subdir/file2.txt"), b"content2")
            .await
            .unwrap();

        let entries = scan_directory(root, None).await.unwrap();

        assert_eq!(entries.len(), 3);

        let names: Vec<_> = entries.iter().map(|e| e.name.clone()).collect();
        assert!(names.contains(&"file1.txt".to_string()));
        assert!(names.contains(&"subdir".to_string()));
        assert!(names.contains(&"subdir/file2.txt".to_string()));
    }

    #[tokio::test]
    async fn test_scan_directory_with_ignore() {
        let temp_dir = TempDir::new().unwrap();
        let root = temp_dir.path();

        // Create test structure
        fs::create_dir(root.join("ignored_dir")).await.unwrap();
        fs::create_dir(root.join("kept_dir")).await.unwrap();
        fs::write(root.join("ignored.txt"), b"ignored").await.unwrap();
        fs::write(root.join("kept.txt"), b"kept").await.unwrap();
        fs::write(root.join("ignored_dir/nested.txt"), b"nested")
            .await
            .unwrap();
        fs::write(root.join("kept_dir/nested.txt"), b"nested")
            .await
            .unwrap();

        let mut patterns = IgnorePatterns::new();
        patterns.add_pattern("ignored_dir/").unwrap();
        patterns.add_pattern("ignored.txt").unwrap();

        let entries = scan_directory(root, Some(&patterns)).await.unwrap();

        let names: Vec<_> = entries.iter().map(|e| e.name.clone()).collect();
        assert!(!names.contains(&"ignored_dir".to_string()));
        assert!(!names.contains(&"ignored_dir/nested.txt".to_string()));
        assert!(!names.contains(&"ignored.txt".to_string()));
        assert!(names.contains(&"kept_dir".to_string()));
        assert!(names.contains(&"kept_dir/nested.txt".to_string()));
        assert!(names.contains(&"kept.txt".to_string()));
    }

    #[tokio::test]
    async fn test_scan_directory_with_negation_no_skip() {
        let temp_dir = TempDir::new().unwrap();
        let root = temp_dir.path();

        fs::create_dir(root.join("ignored_dir")).await.unwrap();
        fs::write(root.join("ignored_dir/nested.txt"), b"nested")
            .await
            .unwrap();

        let mut patterns = IgnorePatterns::new();
        patterns.add_pattern("ignored_dir/").unwrap();
        patterns.add_pattern("!ignored_dir/nested.txt").unwrap();

        // allows_skipping_ignored_dirs should be false due to negation
        assert!(!patterns.allows_skipping_ignored_dirs());

        let entries = scan_directory(root, Some(&patterns)).await.unwrap();

        let names: Vec<_> = entries.iter().map(|e| e.name.clone()).collect();
        // Directory itself should be ignored (not in results)
        assert!(!names.contains(&"ignored_dir".to_string()));
        // But the nested file should be included because of the negation pattern
        assert!(names.contains(&"ignored_dir/nested.txt".to_string()));
    }

    #[tokio::test]
    async fn test_verify_file_success() {
        let temp_dir = TempDir::new().unwrap();
        let file_path = temp_dir.path().join("verify.txt");

        let content = b"verify this content";
        fs::write(&file_path, content).await.unwrap();

        let info = scan_file(&file_path, DEFAULT_BLOCK_SIZE).await.unwrap();
        let hashes: Vec<_> = info.blocks.iter().map(|b| {
            let bytes: [u8; 32] = b.hash.as_slice().try_into().unwrap();
            BlockHash::from_bytes(bytes)
        }).collect();

        // Should succeed
        verify_file(&file_path, &hashes, DEFAULT_BLOCK_SIZE)
            .await
            .unwrap();
    }

    #[tokio::test]
    async fn test_verify_file_failure() {
        let temp_dir = TempDir::new().unwrap();
        let file_path = temp_dir.path().join("verify.txt");

        fs::write(&file_path, b"original content").await.unwrap();
        let info = scan_file(&file_path, DEFAULT_BLOCK_SIZE).await.unwrap();
        let hashes: Vec<_> = info.blocks.iter().map(|b| {
            let bytes: [u8; 32] = b.hash.as_slice().try_into().unwrap();
            BlockHash::from_bytes(bytes)
        }).collect();

        // Modify the file
        fs::write(&file_path, b"modified content").await.unwrap();

        // Should fail
        let result = verify_file(&file_path, &hashes, DEFAULT_BLOCK_SIZE).await;
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_scan_nonexistent_file() {
        let temp_dir = TempDir::new().unwrap();
        let file_path = temp_dir.path().join("nonexistent.txt");

        let result = scan_file(&file_path, DEFAULT_BLOCK_SIZE).await;
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_scan_directory_not_file() {
        let temp_dir = TempDir::new().unwrap();

        let result = scan_file(temp_dir.path(), DEFAULT_BLOCK_SIZE).await;
        assert!(result.is_err());
    }
}
