[package]
name = "syncthing-fs"
version.workspace = true
edition = "2021"
authors = ["juice094"]
description = "Filesystem abstraction and monitoring for Syncthing Rust"
license = "MIT"


publish = false

[dependencies]
syncthing-core = { path = "../syncthing-core" }

# 异步
tokio = { workspace = true }
async-trait = { workspace = true }

# 文件监控
notify = { workspace = true }

# 工具
tracing = { workspace = true }
walkdir = { workspace = true }
num_cpus = { workspace = true }
rayon = { workspace = true }
regex = "1.10"
libc = "0.2"



[dev-dependencies]
tokio-test = "0.4"
tempfile = { workspace = true }
criterion = { workspace = true }
sha2 = { workspace = true }

[[bench]]
name = "scanner"
harness = false

[[bench]]
name = "hash_parallel"
harness = false
